name: Manual Trigger Workflow

# configure manual trigger
on:
  workflow_dispatch:
  schedule:
    - cron: '15 23 25 7 *'

jobs:
  UAT Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          npm install
