name: Manual Trigger Workflow

# configure manual trigger
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  schedule:
      - cron: '00 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          npm install
