name: GitHubActions Job Schedule Automation Tests.

# configure manual trigger, push event, pull_request event and daily nightly execution.
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  
  schedule: ## Schedule the job to run at 12.am daily.
    - cron: '*/5 * * * *'
  
jobs:
  UAT-Smoke-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Smoke Tests
        run: |
          npm install
