name: Manual Trigger Workflow

# configure manual trigger
on: 
  schedule:
  - cron: '*/5 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: { ref: debug }
      - name: Build project
        run: |
          npm install
